# Generated by Django 4.1.1 on 2022-09-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('title', models.TimeField(max_length=225)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
