# Generated by Django 4.1.1 on 2022-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_home_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='subhead',
            field=models.TextField(max_length=225),
        ),
    ]
