# Generated by Django 4.1.1 on 2022-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_main_subhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='heading',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='img1',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='main',
            name='subhead',
            field=models.TextField(max_length=225, null=True),
        ),
    ]
