# Generated by Django 4.1.1 on 2022-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_main_heading_alter_main_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='img1',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
