# Generated by Django 4.1.1 on 2022-10-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_main_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
