# Generated by Django 4.1.1 on 2022-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_main_heading_alter_main_subhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='heading',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
