# Generated by Django 4.1.1 on 2022-10-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_education_experience_delete_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='education',
            name='passout',
            field=models.CharField(max_length=225),
        ),
    ]
