# Generated by Django 4.1.1 on 2022-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_education_cgpa_alter_education_passout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='skills',
        ),
        migrations.AlterField(
            model_name='experience',
            name='disc',
            field=models.TextField(max_length=2223),
        ),
    ]
