# Generated by Django 4.1.1 on 2022-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
