# Generated by Django 4.1.1 on 2022-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_skill_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
    ]
