# Generated by Django 4.1.1 on 2022-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_resume_remove_skill_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='descrip',
            field=models.TextField(default=1, max_length=2224),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='img2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='projlink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
