# Generated by Django 4.1.1 on 2022-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_projects_descrip_projects_img2_projects_projlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projtittle',
            field=models.CharField(default=1, max_length=223),
            preserve_default=False,
        ),
    ]
