# Generated by Django 4.1.1 on 2022-10-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_projects_projtittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projtittle',
            new_name='projtitle',
        ),
    ]
