# Generated by Django 4.1.1 on 2022-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_projtittle_projects_projtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='img3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
