# Generated by Django 4.1.1 on 2022-10-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_projects_img3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='img3',
        ),
    ]
