# Generated by Django 4.1.1 on 2022-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_projects_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField()),
                ('ig', models.URLField()),
                ('ln', models.URLField()),
                ('gh', models.URLField()),
            ],
        ),
    ]
