# Generated by Django 4.1.1 on 2022-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_contact_des_contact_email_contact_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=224)),
                ('pname', models.CharField(max_length=224)),
                ('descr', models.TextField()),
            ],
        ),
    ]
