# Generated by Django 4.1.1 on 2022-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='curl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
