# Generated by Django 4.1.1 on 2022-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_achievements_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='adesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hname',
            field=models.TextField(max_length=1000),
        ),
    ]
