# Generated by Django 4.1.1 on 2022-10-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_achievements_adesc_alter_hobbies_hname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='des',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=2254),
            preserve_default=False,
        ),
    ]
