# Generated by Django 4.1.1 on 2022-10-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_des_contact_message_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='msg',
        ),
    ]
