# Generated by Django 4.1.1 on 2022-10-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_message_contact_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
