# Generated by Django 4.1.1 on 2022-10-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_fullname_contact_name_remove_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mail',
        ),
    ]
