# Generated by Django 4.1.1 on 2022-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_email_contact_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img2',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
