# Generated by Django 4.1.1 on 2022-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_main_img1_alter_projects_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='imgae/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img2',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
